### ISSUE TITLE
pods依赖的问题，指定了固定的SDWebImage版本

### ISSUE THREAD

**Issue by yanmingLiu** [RocketsChen/CDDGroupAvatar#1]
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.2.3)

  In Podfile:
    CDDGroupAvatar was resolved to 1.5.2, which depends on
      SDWebImage (~> 5.0.0)

**Comment by RocketsChen** [comment]
已处理

**Comment by yanmingLiu** [comment]
> 已处理

nice
