### ISSUE TITLE
是否考虑加一个内边距?

### ISSUE THREAD

**Issue by rgmyyw** [RocketsChen/CDDGroupAvatar#2]
大佬, 可以添加一个内边距吗? 
我看您的代码里面是使用的distanceBetweenAvatar 来作为两边边距的, 但其实在业务场景有可能需要控制内边距

期望:  添加一个 UIEdgeInset 属性, 可以控制 头像距离容器的上下左右边距

**Comment by RocketsChen** [comment]
如果你只是想中间每个单独头像的中间间隔和最外层间隔不等是可以框架内部新增个属性去处理，如果用想去UIEdgeInset（上下左右不等情况），建议外层重写UIImageView分类方法，并且需要contentModel建议设置成center。
